/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useState } from "react";
import { supabase } from "@/lib/supabase";
import { CircleAlert, FileDown, LoaderCircle } from "./icons";

const headers=["record_type","id","address","city","state","zip","latitude","longitude","company_name","contact_name","contact_type","phone","email","website","source","status","property_type","notes","tags","relationships","created_at","updated_at"];
function csvCell(value:unknown){let text=Array.isArray(value)?value.join(" | "):String(value??"");if(typeof value!=="number"&&/^[=+\-@\t\r]/.test(text))text=`'${text}`;return `"${text.replaceAll('"','""')}"`}
function relationship(link:any,other:"contacts"|"properties"){const record=link?.[other];if(other==="contacts")return `${link.relationship_type}: ${record?.company_name||record?.contact_name||"Unnamed contact"} (${record?.id||""})`;return `${link.relationship_type}: ${record?.address||"Property"} (${record?.id||""})`}

export function DataExport(){const [exporting,setExporting]=useState(false),[error,setError]=useState("");async function download(){setExporting(true);setError("");const [properties,contacts]=await Promise.all([supabase.from("properties").select("id,address,city,state,zip,latitude,longitude,source,status,property_type,notes,condition_tags,created_at,updated_at,property_contacts(relationship_type,contacts(id,company_name,contact_name))").order("created_at"),supabase.from("contacts").select("id,company_name,contact_name,contact_type,phone,email,website,source,found_at_address,latitude,longitude,notes,created_at,updated_at,property_contacts(relationship_type,properties(id,address))").order("created_at")]);if(properties.error||contacts.error){setError(properties.error?.message||contacts.error?.message||"Export failed.");setExporting(false);return}const rows:any[]=[];for(const item of properties.data??[])rows.push({record_type:"property",...item,tags:item.condition_tags,relationships:item.property_contacts?.map((link:any)=>relationship(link,"contacts"))});for(const item of contacts.data??[])rows.push({record_type:"contact",...item,address:item.found_at_address,relationships:item.property_contacts?.map((link:any)=>relationship(link,"properties"))});const csv="\uFEFF"+[headers.join(","),...rows.map(row=>headers.map(header=>csvCell(row[header])).join(","))].join("\r\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),anchor=document.createElement("a");anchor.href=url;anchor.download=`clay-export-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setExporting(false)}return <section className="section"><h2>Data export</h2><div className="card stack" style={{marginTop:12}}><div><div className="cardtitle">Download a complete CSV backup</div><p className="small muted">Includes properties, contacts, coordinates, notes, tags, and linked relationships.</p></div>{error&&<div className="error card"><CircleAlert/> {error}</div>}<button className="secondary" onClick={download} disabled={exporting}>{exporting?<LoaderCircle className="spin"/>:<FileDown/>}{exporting?"Preparing export…":"Export CSV"}</button></div></section>}
