"use client";

import { ArrowRight, Building2, Camera, Check, MapPinned, Route, Search, ShieldCheck, SignalLow, Sparkles } from "lucide-react";

export function LandingPage({onSignIn}:{onSignIn:()=>void}){
  return <main className="landing">
    <nav className="landingnav"><a className="landinglogo" href="#top">clay</a><div className="landinglinks"><a href="#workflow">How it works</a><a href="#features">Features</a><a href="#field">Built for the field</a></div><button className="landinglogin" onClick={onSignIn}>Sign in <ArrowRight/></button></nav>
    <section className="landinghero" id="top"><div className="herocopy"><div className="landingeyebrow"><Sparkles/>Real estate field intelligence</div><h1>Turn every drive into your next deal.</h1><p>Capture distressed properties, organize owner research, map your routes, and move opportunities forward—all from one focused workspace.</p><div className="heroactions"><button className="landingcta" onClick={onSignIn}>Open your field desk <ArrowRight/></button><a className="landingsecondary" href="#workflow">See how Clay works</a></div><div className="heroproof"><span><Check/>Offline capture</span><span><Check/>Invite-only access</span><span><Check/>Built for mobile</span></div></div>
      <div className="productstage" aria-label="Clay product preview"><div className="stageglow"/><div className="phoneframe"><div className="phonebar"><span>clay</span><small>FIELD DESK</small></div><div className="phoneheadline">Capture today.<br/>Close tomorrow.</div><div className="phonestats"><span><b>24</b>Properties</span><span><b>12</b>Research</span><span><b>3</b>Deals</span></div><div className="routepreview"><div className="routegrid"/><Route/><i className="routepath"/><span className="routepin one"/><span className="routepin two"/><span className="routepin three"/><div><b>Drive in progress</b><small>4.8 mi · 7 properties</small></div></div><div className="leadpreview"><div className="leadicon"><Building2/></div><div><b>2750 Creston Avenue</b><small>Hot lead · 87% researched</small></div><strong>92</strong></div></div>
      <div className="floatingcard floatingone"><Camera/><span><b>Property captured</b><small>Saved with location</small></span></div><div className="floatingcard floatingtwo"><Search/><span><b>Research complete</b><small>Owner and zoning found</small></span></div></div>
    </section>

    <section className="landingstrip"><span>DRIVE FOR DOLLARS</span><i/><span>PROPERTY RESEARCH</span><i/><span>CONTACT CRM</span><i/><span>DEAL PIPELINE</span></section>

    <section className="landingsection workflow" id="workflow"><div className="sectionintro"><span className="landingeyebrow">One connected workflow</span><h2>From curbside signal to closed opportunity.</h2><p>Clay keeps the field work and desk work together, so valuable context never gets lost between apps or spreadsheets.</p></div><div className="workflowgrid">{[
      ["01","Capture",Camera,"Save an address, coordinates, condition tags, notes, and photos in seconds—even when connectivity drops."],
      ["02","Research",Search,"Build a complete property file with ownership, zoning, taxes, comps, contacts, sources, and documents."],
      ["03","Convert",Building2,"Link buyers and contacts, schedule follow-ups, and move qualified opportunities through your pipeline."]
    ].map(([number,title,Icon,text])=><article className="workflowcard" key={String(number)}><span>{String(number)}</span><div className="workflowicon"><Icon/></div><h3>{String(title)}</h3><p>{String(text)}</p></article>)}</div></section>

    <section className="featureband" id="features"><div className="featurevisual"><div className="mapmock"><div className="maproads"/><span className="dot d1"/><span className="dot d2"/><span className="dot d3"/><span className="dot d4"/><div className="mapcard"><MapPinned/><div><b>Route coverage</b><small>12.4 miles mapped today</small></div></div></div></div><div className="featurecopy"><span className="landingeyebrow">Know every block</span><h2>A field map that remembers where you’ve been.</h2><p>Track drive sessions, visualize covered routes, switch to satellite imagery, and see every saved property by deal status.</p><ul><li><Route/>Live route, elapsed time, and distance</li><li><MapPinned/>Coordinate-based property mapping</li><li><SignalLow/>Reliable offline capture and later sync</li></ul></div></section>

    <section className="landingsection featuregrid" id="field"><article className="featuretile tilewide"><div><span className="landingeyebrow">Research workspace</span><h2>Build a defensible property file.</h2><p>Check off every research area, retain source links and notes, attach records, score opportunities, and download a polished property brief.</p></div><div className="checkmock">{["Owner & mailing address","Zoning & development","Taxes, liens & mortgages","Comps & buyer matches"].map((x,i)=><div key={x}><span className={i<3?"done":""}>{i<3&&<Check/>}</span>{x}<small>{i<3?"Complete":"In progress"}</small></div>)}</div></article><article className="featuretile"><ShieldCheck/><h3>Private by design</h3><p>Invite-only accounts, verified profile changes, row-level data security, and isolated user records.</p></article><article className="featuretile"><SignalLow/><h3>Made for imperfect signal</h3><p>Capture properties and photos offline, then synchronize them when your connection returns.</p></article></section>

    <section className="landingfinal"><div><span className="landingeyebrow">Your field desk is ready</span><h2>Spend less time organizing.<br/>Find more opportunities.</h2></div><button className="landingcta" onClick={onSignIn}>Sign in to Clay <ArrowRight/></button></section>
    <footer className="landingfooter"><a className="landinglogo" href="#top">clay</a><p>Capture today. Close tomorrow.</p><span>Private real estate research software.</span></footer>
  </main>
}
