/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect,useState } from "react";
import { supabase } from "@/lib/supabase";
import { Check,CircleAlert,Plus,X } from "./icons";

export type RecordField={key:string;label:string;type?:"text"|"number"|"date"|"datetime-local"|"textarea"|"select"|"checkbox";options?:string[];placeholder?:string};
export function ResearchRecords({table,title,propertyId,userId,fields,order="created_at",ascending=false,defaults={},onChanged,renderExtra}:{table:string;title:string;propertyId:string;userId:string;fields:RecordField[];order?:string;ascending?:boolean;defaults?:Record<string,any>;onChanged?:()=>void;renderExtra?:(row:any)=>React.ReactNode}){
  const blank=()=>Object.fromEntries(fields.map(field=>[field.key,defaults[field.key]??(field.type==="checkbox"?false:"")]));
  const [rows,setRows]=useState<any[]>([]),[draft,setDraft]=useState<Record<string,any>>(blank),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false);
  async function load(){const result=await supabase.from(table).select("*").eq("property_id",propertyId).order(order,{ascending});if(result.error)setError(result.error.message);else setRows(result.data??[])}
  // The async callback resolves after the effect and hydrates this table's local editor.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(()=>{void load()},[propertyId,table]);
  async function save(){setSaving(true);setError("");const payload:any={...draft,property_id:propertyId,user_id:userId,created_by:userId,updated_at:new Date().toISOString()};for(const field of fields){if(field.type==="number")payload[field.key]=payload[field.key]===""?null:Number(payload[field.key]);if((field.type==="date"||field.type==="datetime-local")&&payload[field.key]==="")payload[field.key]=null}const result=editing?await supabase.from(table).update(payload).eq("id",editing):await supabase.from(table).insert(payload);if(result.error)setError(result.error.message);else{setDraft(blank());setEditing(null);await load();onChanged?.()}setSaving(false)}
  function edit(row:any){setEditing(row.id);setDraft(Object.fromEntries(fields.map(field=>[field.key,row[field.key]??(field.type==="checkbox"?false:"")])))}
  async function remove(id:string){const result=await supabase.from(table).delete().eq("id",id);if(result.error)setError(result.error.message);else{await load();onChanged?.()}}
  return <div className="subsection"><div className="sectionhead"><h3>{title}</h3><span className="small muted">{rows.length} saved</span></div>{rows.length>0&&<div className="recordlist">{rows.map(row=><div className="recordcard" key={row.id}><button className="recordbody" type="button" onClick={()=>edit(row)}>{fields.slice(0,4).map(field=>row[field.key]!==null&&row[field.key]!==""&&<span key={field.key}><small>{field.label}</small>{field.type==="checkbox"?(row[field.key]?"Yes":"No"):String(row[field.key])}</span>)}</button>{renderExtra?.(row)}<button type="button" className="removeplain" aria-label={`Remove ${title} record`} onClick={()=>remove(row.id)}><X/></button></div>)}</div>}<div className="recordform">{fields.map(field=><div className={field.type==="textarea"?"field full":"field"} key={field.key}><label>{field.label}</label>{field.type==="select"?<select className="input" value={draft[field.key]} onChange={e=>setDraft({...draft,[field.key]:e.target.value})}><option value="">Select…</option>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:field.type==="textarea"?<textarea className="input" value={draft[field.key]} placeholder={field.placeholder} onChange={e=>setDraft({...draft,[field.key]:e.target.value})}/>:field.type==="checkbox"?<label className="toggle"><input type="checkbox" checked={Boolean(draft[field.key])} onChange={e=>setDraft({...draft,[field.key]:e.target.checked})}/><span>{draft[field.key]?"Yes":"No"}</span></label>:<input className="input" type={field.type??"text"} value={draft[field.key]} placeholder={field.placeholder} onChange={e=>setDraft({...draft,[field.key]:e.target.value})}/>}</div>)}</div>{error&&<div className="card error"><CircleAlert/> {error}</div>}<div className="twocol compactactions"><button type="button" className="secondary" onClick={save} disabled={saving}>{editing?<Check/>:<Plus/>}{saving?"Saving…":editing?"Update record":`Add ${title.replace(/s$/,"")}`}</button>{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setDraft(blank())}}><X/>Cancel edit</button>}</div></div>;
}
