import { supabase } from "./supabase";
import { coordinatesFromAddress } from "./geocoding";
import { createUuid } from "./id";
import { findDuplicateProperty } from "./property-duplicates";

export type OfflineKind="property"|"contact";
export type OfflinePhoto={blob:Blob;name:string;originalName:string};
export type OfflineItem={id:string;userId:string;kind:OfflineKind;payload:Record<string,unknown>;photos:OfflinePhoto[];createdAt:string;attempts:number;lastError?:string};
const DB_NAME="clay-field-queue",STORE="captures",VERSION=1;

function database():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:"id"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function notify(){window.dispatchEvent(new CustomEvent("clay-queue-change"))}
export async function queueCapture(input:Omit<OfflineItem,"id"|"createdAt"|"attempts">){const item:OfflineItem={...input,id:createUuid(),createdAt:new Date().toISOString(),attempts:0};const db=await database();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(item);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close();notify();return item}
export async function queuedCaptures():Promise<OfflineItem[]>{const db=await database();const rows=await new Promise<OfflineItem[]>((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();return rows.sort((a,b)=>a.createdAt.localeCompare(b.createdAt))}
async function removeCapture(id:string){const db=await database();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}
async function updateCapture(item:OfflineItem){const db=await database();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(item);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}

export async function syncQueue(userId:string){if(!navigator.onLine)return {synced:0,remaining:(await queuedCaptures()).length};let synced=0;for(const item of await queuedCaptures()){if(item.userId!==userId)continue;try{const table=item.kind==="property"?"properties":"contacts",payload={...item.payload};if(!payload.latitude&&!payload.longitude){const address=item.kind==="property"?[payload.address,payload.city,payload.state,payload.zip].filter(Boolean).join(", "):String(payload.found_at_address??"");if(address){const match=await coordinatesFromAddress(address);if(match){payload.latitude=match.latitude;payload.longitude=match.longitude}}}if(item.kind==="property"){const duplicate=await findDuplicateProperty({address:String(payload.address??""),city:String(payload.city??""),state:String(payload.state??""),zip:String(payload.zip??""),latitude:payload.latitude==null?null:Number(payload.latitude),longitude:payload.longitude==null?null:Number(payload.longitude),excludeId:String(payload.id??"")});if(duplicate?.reason==="address")throw new Error("Possible duplicate property at "+duplicate.address+". Review the queued capture before syncing.")}const {data,error}=await supabase.from(table).upsert(payload,{onConflict:"id"}).select("id").single();if(error)throw error;for(const photo of item.photos){const folder=item.kind==="property"?"properties":"contacts",path=`users/${userId}/${folder}/${data.id}/${photo.name}`;await supabase.storage.from("property-media").remove([path]);const upload=await supabase.storage.from("property-media").upload(path,photo.blob,{contentType:"image/jpeg"});if(upload.error)throw upload.error;const photoTable=item.kind==="property"?"property_photos":"contact_photos",foreignKey=item.kind==="property"?"property_id":"contact_id";const metadata=await supabase.from(photoTable).upsert({user_id:userId,[foreignKey]:data.id,storage_path:path,file_name:photo.originalName,mime_type:"image/jpeg",size_bytes:photo.blob.size},{onConflict:"storage_path"});if(metadata.error)throw metadata.error}await removeCapture(item.id);synced++}catch(reason){item.attempts++;item.lastError=reason instanceof Error?reason.message:String(reason);await updateCapture(item)}}notify();return {synced,remaining:(await queuedCaptures()).length}}
