import { createHash, randomInt } from "node:crypto";
import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

export const runtime = "nodejs";
function clients(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,service=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!anon||!service)throw new Error("Phone verification is not configured on the server.");return {auth:createClient(url,anon,{auth:{persistSession:false}}),admin:createClient(url,service,{auth:{persistSession:false}})}}
function hash(userId:string,code:string){return createHash("sha256").update(`${userId}:${code}`).digest("hex")}

export async function POST(request:Request){try{const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token)return NextResponse.json({error:"Sign in again before changing your phone number."},{status:401});const {auth,admin}=clients(),{data:{user},error:userError}=await auth.auth.getUser(token);if(userError||!user?.email)return NextResponse.json({error:"Your signed-in account could not be verified."},{status:401});const {phone}=await request.json(),normalized=String(phone??"").trim();if(!/^\+[1-9]\d{7,14}$/.test(normalized))return NextResponse.json({error:"Enter a valid phone number including its country code."},{status:400});const code=String(randomInt(100000,1000000)),expiresAt=new Date(Date.now()+10*60_000).toISOString();const stored=await admin.from("profile_change_codes").upsert({user_id:user.id,kind:"phone",pending_value:normalized,code_hash:hash(user.id,code),expires_at:expiresAt,attempts:0},{onConflict:"user_id,kind"});if(stored.error)throw stored.error;const apiKey=process.env.RESEND_API_KEY,from=process.env.CLAY_EMAIL_FROM,recipient=process.env.CLAY_EMAIL_TEST_RECIPIENT?.trim()||user.email;if(!apiKey||!from)throw new Error("Email delivery is not configured. Add RESEND_API_KEY and CLAY_EMAIL_FROM.");const sent=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[recipient],subject:"Verify your Clay phone-number change",html:`<div style="font-family:Arial,sans-serif;color:#17191c"><h2>Verify your phone-number change</h2><p>Enter this code in Clay to save <strong>${normalized}</strong>:</p><p style="font-size:30px;font-weight:700;letter-spacing:6px">${code}</p><p>This code expires in 10 minutes. If you did not request this change, you can ignore this email.</p>${recipient!==user.email?`<p style="color:#8a641f"><strong>Testing mode:</strong> this code was requested by the Clay account ${user.email}.</p>`:""}</div>`})});if(!sent.ok)throw new Error(`Email could not be sent. ${await sent.text()}`);return NextResponse.json({ok:true,email:recipient})}catch(reason){return NextResponse.json({error:reason instanceof Error?reason.message:"Phone verification could not be started."},{status:500})}}
