create extension if not exists pgcrypto;

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text, full_name text not null default '', phone text not null default '', onboarding_completed boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.properties (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, address text not null, city text default '', state text default '', zip text default '', latitude double precision, longitude double precision, gps_accuracy double precision, source text not null default 'Drive for Dollars', property_type text not null default 'Single Family', status text not null default 'New', notes text default '', condition_tags text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.property_photos (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, property_id uuid not null references public.properties(id) on delete cascade, storage_path text not null unique, file_name text, mime_type text, size_bytes bigint, created_at timestamptz not null default now());
create table public.contacts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, company_name text default '', contact_name text default '', contact_type text default 'Other', phone text default '', email text default '', website text default '', source text default 'Other', found_at_address text default '', latitude double precision, longitude double precision, notes text default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.contact_photos (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, contact_id uuid not null references public.contacts(id) on delete cascade, storage_path text not null unique, file_name text, mime_type text, size_bytes bigint, created_at timestamptz not null default now());
create table public.buy_boxes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, contact_id uuid not null unique references public.contacts(id) on delete cascade, areas_markets text default '', property_types text default '', minimum_price numeric, maximum_price numeric, minimum_lot_size text default '', preferred_zoning text default '', assemblages text default 'unknown' check (assemblages in ('yes','no','unknown')), notes text default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.contact_activities (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, contact_id uuid not null references public.contacts(id) on delete cascade, type text not null check (type in ('Call','Email','Meeting','Note','Follow Up')), notes text default '', occurred_at timestamptz not null default now(), follow_up_date date, created_at timestamptz not null default now());
create table public.property_contacts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, property_id uuid not null references public.properties(id) on delete cascade, contact_id uuid not null references public.contacts(id) on delete cascade, relationship_type text default 'Other', created_at timestamptz not null default now(), unique(property_id,contact_id));
create table public.tasks (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, assigned_to uuid references auth.users(id) on delete set null, title text not null, notes text not null default '', priority text not null default 'Normal' check (priority in ('Low','Normal','High','Urgent')), status text not null default 'Open' check (status in ('Open','Completed')), due_at timestamptz, reminder_at timestamptz, property_id uuid references public.properties(id) on delete cascade, contact_id uuid references public.contacts(id) on delete cascade, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (not (property_id is not null and contact_id is not null)));

create index properties_user_created_idx on public.properties(user_id,created_at desc); create index properties_user_status_idx on public.properties(user_id,status); create index contacts_user_created_idx on public.contacts(user_id,created_at desc); create index contact_activities_contact_idx on public.contact_activities(contact_id,occurred_at desc); create index property_photos_property_idx on public.property_photos(property_id); create index contact_photos_contact_idx on public.contact_photos(contact_id); create index property_contacts_property_idx on public.property_contacts(property_id); create index property_contacts_contact_idx on public.property_contacts(contact_id);
create index tasks_user_status_due_idx on public.tasks(user_id,status,due_at); create index tasks_user_reminder_idx on public.tasks(user_id,reminder_at) where status='Open'; create index tasks_property_idx on public.tasks(property_id) where property_id is not null; create index tasks_contact_idx on public.tasks(contact_id) where contact_id is not null;

alter table public.profiles enable row level security; alter table public.properties enable row level security; alter table public.property_photos enable row level security; alter table public.contacts enable row level security; alter table public.contact_photos enable row level security; alter table public.buy_boxes enable row level security; alter table public.contact_activities enable row level security; alter table public.property_contacts enable row level security;
alter table public.tasks enable row level security;
create policy "profiles own rows" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy "properties own rows" on public.properties for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "property photos own rows" on public.property_photos for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "contacts own rows" on public.contacts for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "contact photos own rows" on public.contact_photos for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "buy boxes own rows" on public.buy_boxes for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "activities own rows" on public.contact_activities for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "links own rows" on public.property_contacts for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "tasks own rows" on public.tasks for all using (auth.uid()=user_id) with check (auth.uid()=user_id);

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values ('property-media','property-media',false,10485760,array['image/jpeg','image/png','image/webp']) on conflict (id) do update set public=false;
create policy "users upload own media" on storage.objects for insert to authenticated with check (bucket_id='property-media' and (storage.foldername(name))[1]='users' and (storage.foldername(name))[2]=auth.uid()::text);
create policy "users view own media" on storage.objects for select to authenticated using (bucket_id='property-media' and (storage.foldername(name))[1]='users' and (storage.foldername(name))[2]=auth.uid()::text);
create policy "users delete own media" on storage.objects for delete to authenticated using (bucket_id='property-media' and (storage.foldername(name))[1]='users' and (storage.foldername(name))[2]=auth.uid()::text);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name,phone) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.raw_user_meta_data->>'phone','')); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
